services:
  spring_security_service:
    container_name: spring-security-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - spring_security_ntk
    depends_on:
      postgresql_service:
        condition: service_healthy

  postgresql_service:
    container_name: postgres-sql-container
    build: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - pg_sql_data:/var/lib/pg_sql
    networks:
      - spring_security_ntk
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spring_security_db

networks:
    spring_security_ntk:
      name: spring-security-network
      driver: bridge

volumes:
  pg_sql_data:
    name: pg-sql-data-volume